### PR TITLE
Rebase upstream

### PR DESCRIPTION
**Pull request by joshgillies**
🐋

Specifically some changes upstream were made to enable support for the new Lambda `nodejs10.x` runtime. This PR is to enable support for that runtime.

### CODE REVIEW

**Comment by joshgillies** [comment]
Running the `ansible` task now, will test it out by creating new layer once finished.

**Comment by joshgillies** [comment]
Successfully built a new version of Chromium and have now updated out AWS Lambda Layer by following steps outlined in the official docs 🎉

**Comment by wbowling** [comment]
What's the normal process with forks and master, should they be kept in sync or is master just the version that we will be using

**Review by wbowling — APPROVED** [review]
:shipit:

**Comment by joshgillies** [comment]
@wbowling good catch! I actually intended to merge this branch into `proprietary-codecs`!

**Comment by joshgillies** [comment]
With regard to what we should do with `master`, I'm open to possibilities. But am happy to just make `proprietary-codecs` the default branch for our fork, and fingers crossed this lands https://github.com/alixaxel/chrome-aws-lambda/pull/68 then we can just nuke this fork altogether.

**Comment by joshgillies** [comment]
Oh... I see you've submitted the above PR as a merge request against `Biteable:proprietary-codecs`, in that case we might want to leave it and target `master` with this PR... why is nothing straight forward? ;P

**Comment by joshgillies** [comment]
OK. merging this into `master` preserving `proprietary-codecs` for https://github.com/alixaxel/chrome-aws-lambda/pull/68. Sorry for the run around!

**Review by wbowling — APPROVED** [review]
:shipit:

**Pull request merged**
